//
//  SongCommentRouter.swift
//  Dotify
//
//  Created Pham Thanh Phat on 7/28/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SongCommentRouter: SongCommentWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SongCommentViewController(nibName: nil, bundle: nil)
        let interactor = SongCommentInteractor()
        let router = SongCommentRouter()
        let presenter = SongCommentPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
