//
//  SongCommentViewController.swift
//  Dotify
//
//  Created Pham Thanh Phat on 7/28/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SongCommentViewController: UIViewController, SongCommentViewProtocol {
    @IBOutlet weak var commentTableView: UITableView!
    @IBOutlet weak var inputTextField: UITextField!
    @IBOutlet weak var sendButton: UIButton!
    @IBOutlet weak var bottomConstrain: NSLayoutConstraint!
    
	var presenter: SongCommentPresenterProtocol?
    var songID: String?
    let cellId = "CommentCell"
    var comments: [Comment] = []

	override func viewDidLoad() {
        super.viewDidLoad()
        commentTableView.dataSource = self
        commentTableView.delegate = self
        
        //register cell
        let cellNib = UINib(nibName: "CommentCell", bundle: nil)
        commentTableView.register(cellNib, forCellReuseIdentifier: cellId)
        NotificationCenter.default.addObserver(self, selector: #selector(keyBoardWillShow(_:)), name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyBoardWillHide(_:)), name: UIResponder.keyboardWillHideNotification, object: nil)
    }
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        presenter?.loadAllComment(songId: AudioPlaying.ins.currentIDSong()!, { (comments, error) in
            guard error == nil else { presentAlertVC(target: self, title: "Error", message: error!.localizedDescription, nil); return }
            self.comments = comments
            self.commentTableView.reloadData()
        })
    }
    //MARK: Action
    @IBAction func didTapSend(_ sender: Any) {
        if let content = inputTextField.text {
            if content.isEmpty { return }
            presenter?.sendComment(songId: AudioPlaying.ins.currentIDSong()!, content: content, { (error) in
                guard error == nil else { presentAlertVC(target: self, title: "Error", message: error!.localizedDescription, nil); return }
                self.presenter?.loadAllComment(songId: AudioPlaying.ins.currentIDSong()!, { (comments, error) in
                    guard error == nil else { presentAlertVC(target: self, title: "Error", message: error!.localizedDescription, nil); return }
                    self.comments = comments
                    self.commentTableView.reloadData()
                    self.inputTextField.text = ""
                })
            })
        }
    }
    
    @objc func keyBoardWillShow(_ notification: Notification){
        if let keyboardFrame = notification.userInfo![UIResponder.keyboardFrameEndUserInfoKey] as? NSValue {
            let keyboardHeight = keyboardFrame.cgRectValue.height
            bottomConstrain.constant = keyboardHeight + 10
        }
    }
    @objc func keyBoardWillHide(_ notification: Notification){
        bottomConstrain.constant = 10
    }
}

extension SongCommentViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return comments.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: cellId, for: indexPath) as? CommentCell else { return UITableViewCell() }
        cell.setUpView(comment: comments[indexPath.row])
        return cell
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}
