//
//  SongCommentProtocols.swift
//  Dotify
//
//  Created Pham Thanh Phat on 7/28/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SongCommentWireframeProtocol: class {

}
//MARK: Presenter -
protocol SongCommentPresenterProtocol: class {
    func loadAllComment(songId: String, _ completion: @escaping ([Comment], Error?) -> Void )
    func sendComment(songId: String, content: String, _ completion: @escaping (Error?) -> Void)
}

//MARK: Interactor -
protocol SongCommentInteractorProtocol: class {

    var presenter: SongCommentPresenterProtocol?  { get set }
    func addComment(userId: String, songId: String, content: String, _ completion: @escaping (Error?)-> Void)
    func loadComments(of songId: String, _ completion: @escaping ([Comment], Error?) -> Void)
    func loadUser(with id: String, _ completion: @escaping (User?, Error?) -> Void)
}

//MARK: View -
protocol SongCommentViewProtocol: class {

  var presenter: SongCommentPresenterProtocol?  { get set }
}
