//
//  SearchRouter.swift
//  Dotify
//
//  Created Lucas Pham on 7/24/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchRouter: SearchWireframeProtocol {
    
    weak var viewController: SearchViewController?
    
    static func createModule(miniPlayer: MiniPlayerViewController?) -> SearchViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SearchViewController(nibName: nil, bundle: nil)
        let interactor = SearchInteractor()
        let router = SearchRouter()
        let presenter = SearchPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.parentVC = miniPlayer
        return view
    }
}
