//
//  ListPlayListRouter.swift
//  Dotify
//
//  Created Lucas Pham on 7/19/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ListPlayListRouter: ListPlayListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ListPlayListViewController(nibName: nil, bundle: nil)
        let interactor = ListPlayListInteractor()
        let router = ListPlayListRouter()
        let presenter = ListPlayListPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
