//
//  LogInProtocols.swift
//  Dotify
//
//  Created Lucas Pham on 7/12/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LogInWireframeProtocol: class {

}
//MARK: Presenter -
protocol LogInPresenterProtocol: class {
    func logIn(curUser: User ,completion: @escaping (_ result: Bool?, _ error: LogInError?)-> () )
}

//MARK: Interactor -
protocol LogInInteractorProtocol: class {

    var presenter: LogInPresenterProtocol?  { get set }
    func loadAllUser(completion: @escaping (_ users: [User]?, _ error: Error?) -> () )
    func writeIdToLocal(user: User) -> Bool
}

//MARK: View -
protocol LogInViewProtocol: class {

    var presenter: LogInPresenterProtocol?  { get set }
}
