//
//  AudioPlayerRouter.swift
//  Dotify
//
//  Created Lucas Pham on 7/10/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AudioPlayerRouter: AudioPlayerWireframeProtocol {
    
    weak var viewController: AudioPlayerViewController?
    
    static func createModule() -> AudioPlayerViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AudioPlayerViewController(nibName: nil, bundle: nil)
        let interactor = AudioPlayerInteractor()
        let router = AudioPlayerRouter()
        let presenter = AudioPlayerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
