//
//  SignUpRouter.swift
//  Dotify
//
//  Created Lucas Pham on 7/12/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpRouter: SignUpWireframeProtocol {
    
    weak var viewController: SignUpViewController?
    
    static func createModule() -> SignUpViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SignUpViewController(nibName: nil, bundle: nil)
        let interactor = SignUpInteractor()
        let router = SignUpRouter()
        let presenter = SignUpPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
