//
//  SignUpInteractor.swift
//  Dotify
//
//  Created Lucas Pham on 7/12/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Alamofire

class SignUpInteractor: SignUpInteractorProtocol {

    weak var presenter: SignUpPresenterProtocol?
    func addUser(user: User, completion: @escaping (Bool?, Error?) -> ()) {
        //Do something
        UserFirebase.instance.addUser(user: user) { (error, ref) in
            completion(error == nil ? true : false, error)
        }
    }
    
    func loadAllUser(completion: @escaping (_ users: [User]?, _ error: Error?) -> () ){
        var users: [User] = []
        AF.request(UserDataURL.instance.getAllUserJson()).responseJSON { (response) in
            guard response.error == nil else {
                completion(nil, response.error)
                return
            }
            guard let listUserJson = response.value as? [String: Any] else { fatalError("Error while casting json") }
            listUserJson.forEach({ (key, value) in
                guard let userDict = value as? [String: Any] else { fatalError("Error with user data") }
                let user = User.init(JSON: userDict)
                users.append(user!)
            })
            completion(users, nil)
        }
    }
    
//    func checkUserWithData(user: User, completion: @escaping (_ isTaken: Bool?, _ error: Error?) -> () ){
//        AF.request(UserDataURL.instance.getAllUserJson()).responseJSON { (response) in
//            guard response.error == nil else {
//                completion(nil, response.error)
//                return
//            }
//            guard let listUserJson = response.value as? [String: Any] else { fatalError("Error while casting json") }
//            listUserJson.forEach({ (key, value) in
//                guard let userDict = value as? [String: Any] else { fatalError("Error with user data") }
//                let curUsername = userDict["username"] as! String
//                let curEmail = userDict["email"] as! String
//
//                let error: Error?
//                if curUsername == user.username {
//
//                }
//
//            })
//        }
//    }
}
