//
//  SignUpProtocols.swift
//  Dotify
//
//  Created Lucas Pham on 7/12/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignUpWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignUpPresenterProtocol: class {
    func signUp(user: User, completion: @escaping (_ isSuccess: Bool?, _ error: Error?) -> () )
}

//MARK: Interactor -
protocol SignUpInteractorProtocol: class {

    var presenter: SignUpPresenterProtocol?  { get set }
    func addUser(user: User, completion: @escaping (_ isSuccess: Bool?, _ error: Error?) -> () )
    func loadAllUser(completion: @escaping (_ users: [User]?, _ error: Error?) -> () )
}

//MARK: View -
protocol SignUpViewProtocol: class {

    var presenter: SignUpPresenterProtocol?  { get set }
    func checkUsername(isTaken: Bool?, invalidFormat: Bool?)
    func checkEmail(isTaken: Bool?, invalidFormat: Bool?)
}
