//
//  MiniPlayerRouter.swift
//  Dotify
//
//  Created Lucas Pham on 7/15/19.
//  Copyright © 2019 Vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MiniPlayerRouter: MiniPlayerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> MiniPlayerViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MiniPlayerViewController(nibName: nil, bundle: nil)
        let interactor = MiniPlayerInteractor()
        let router = MiniPlayerRouter()
        let presenter = MiniPlayerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
